// dart format off
// Generated by tool/generate_constants.dart

// ignore: import_internal_library
import 'dart:_wasm';

import 'string.dart';

/// The string `Stack traces are unavailable in WASM component builds`
const Latin1String stackTracesAreUnavailableMessage = Latin1String.unsafeWrap(WasmArray.literal([83, 116, 97, 99, 107, 32, 116, 114, 97, 99, 101, 115, 32, 97, 114, 101, 32, 117, 110, 97, 118, 97, 105, 108, 97, 98, 108, 101, 32, 105, 110, 32, 87, 65, 83, 77, 32, 99, 111, 109, 112, 111, 110, 101, 110, 116, 32, 98, 117, 105, 108, 100, 115]));
/// The string `0`
const Latin1String $0 = Latin1String.unsafeWrap(WasmArray.literal([48]));
/// Char codes of `0123456789abcdefghijklmnopqrstuvwxyz`
const WasmArray<WasmI8> digits = WasmArray.literal([48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122]);
/// The string `UNKNOWN TZ`
/// The IANA-style id the embedder reports for the local time zone. The
/// runtime always pairs it with a zero offset (`timeZoneOffsetInSecondsForClampedSeconds`
/// in exports.dart is a constant), so the id claims UTC: a name like
/// "UNKNOWN TZ" would disagree with the offset it is reported alongside.
/// See [wasiIanaId] in clock.dart for why it cannot reflect the host zone.
const Latin1String unknownTimezone = Latin1String.unsafeWrap(
  WasmArray.literal([85, 84, 67]),
);
/// The string `cm-root:/`
const Latin1String stubRootUri = Latin1String.unsafeWrap(WasmArray.literal([99, 109, 45, 114, 111, 111, 116, 58, 47]));
