import 'dart:typed_data';

import 'package:logging/logging.dart';

import '../third_party/wasm_builder/wasm_builder.dart' as w;
import '../third_party/wasm_builder/src/builder/util.dart';
import 'abi/abi.dart';
import 'abi/canonical_options.dart';
import 'abi/imported_function.dart';
import 'abi/interface.dart';
import 'abi/linker.dart';
import 'components/definition.dart';
import 'components/index_space.dart';
import 'components/type.dart' as component_types;
import 'compiler.dart';

/// Patches a WebAssembly module generated by `dart2wasm` to reduce host
/// imports.
final class ModuleTransformer {
  final w.Module module;
  final Logger logger;
  final bool implicitWasiDependencies;
  final Map<w.ImportedFunction, w.BaseFunction> _patchFunctions = {};

  late final Map<String, w.Export> _exports = {
    for (final export in module.exports.exported) export.name: export,
  };

  ModuleTransformer(
    this.module,
    this.logger, {
    required this.implicitWasiDependencies,
  });

  factory ModuleTransformer.fromBytes(
    Uint8List moduleBytes,
    Logger logger, {
    required bool implicitWasiDependencies,
  }) {
    return ModuleTransformer(
      w.Module.deserialize(w.Deserializer(moduleBytes)),
      logger,
      implicitWasiDependencies: implicitWasiDependencies,
    );
  }

  Uint8List serialize() {
    final serializer = w.Serializer();
    module.serialize(serializer);
    return serializer.data;
  }

  void transform(ProgramAbi abi) {
    _patchImports(abi);
    final expectedExports = <String>{};
    for (final exported in abi.exportedFunctions) {
      expectedExports.add(exported.name);
      if (exported.options.usesCallback) expectedExports.add('callback');
      if (exported.options.postReturn case final pr?) expectedExports.add(pr);
    }

    _removeExports(expectedExports);
    _runMainOnInstantiation();
  }

  void _patchImports(ProgramAbi abi) {
    const replacers = {
      'randomInt': _RandomImports(),
      'randomIntSecure': _RandomImports(),
      'print': _PrintImports(),
      'wasi_now': _ClockImports(),
      'wasi_iana_id': _ClockImports(),
      'wasi_monotonic_now': _ClockImports(),
      'wasi_monotonic_getResolution': _ClockImports(),
      'wasi_monotonic_waitFor': _ClockImports(),
      'stackTraceGetCurrent': _StackTraceImports(),
      'stackTraceToString': _StackTraceImports(),
      'timelineStreamEnabled': _TimelineImports(),
      'reportTaskEvent': _TimelineImports(),
    };

    // First pass: run the replacers for all `dart.*` imports before anything
    // else looks at `component.*` imports, since the replacers register the
    // implicit `component.implicitImport_*` dependencies in the ABI.
    for (final import in module.imports.all.toList()) {
      if (import is! w.ImportedFunction || import.module != 'dart') continue;
      if (replacers[import.name] case final replacer?) {
        replacer.addTo(abi, this, import);
      }
    }

    // The timeline replacer has one duty the loop above cannot reach: the
    // embedder's `component.implicitImport_timelineReportTaskEvent` import
    // is declared in every module (its source is always compiled in), but
    // when dart2wasm's DCE removed both `dart.*` timeline imports there is
    // no `dart.*` import left to run the replacer with. Decide on the
    // embedder's behalf: with the SDK entries present the dependency was
    // registered above; without them the declared import is rewired to a
    // stub so the component stays free of an unused host dependency.
    const timelineReplacer = _TimelineImports();
    if (!_ComponentImport.functionUsed(this, 'timelineStreamEnabled') &&
        !_ComponentImport.functionUsed(this, 'reportTaskEvent')) {
      final declared = module.imports.functions.firstWhere(
        (import) =>
            import.module == 'component' &&
            import.name == 'implicitImport_timelineReportTaskEvent',
      );
      timelineReplacer._stubTimelineReport(this, declared);
    }

    final unusedComponentImports = {
      for (final import in abi.imports) import.importName,
    };

    for (final import in module.imports.all.toList()) {
      if (import is w.ImportedFunction &&
          _patchFunctions.containsKey(import)) {
        // The import was replaced by a stub or by an ABI import in the first
        // pass; the actual rewrite happens below.
        continue;
      }

      if (import is w.ImportedFunction && import.module == 'dart') {
        if (_exports[import.name] case final export?) {
          if (export case w.FunctionExport(
            function: final w.DefinedFunction fn,
          )) {
            _patchFunctions[import] = fn;
            continue;
          }
        } else if (_rewriteToRuntimeImports.contains(import.name)) {
          import.module = _runtimeImportName;
          import.name = 'dart_${import.name}';
          continue;
        }
      }

      if (import.module == _runtimeImportName) continue;
      if (import.module == 'component') {
        // Implicit dependencies contributed by the replacers above are
        // registered in the ABI, so they can be resolved like any other.
        if (unusedComponentImports.remove(import.name)) {
          continue;
        }

        // These canon. imports are only used in pkg:wasm_components. Other
        // packages encode them in their ABI contributed by build hooks.
        if (import.name.startsWith('canon.')) {
          CanonPrimitive Function(Linker) primitive;

          switch (import.name) {
            case 'canon.context.get_i32_0':
              primitive = (linker) => linker.component.canonContextGet(0);
            case 'canon.context.set_i32_0':
              primitive = (linker) => linker.component.canonContextSet(0);
            case 'canon.waitable-set.new':
              primitive = (linker) =>
                  linker.component.addCanonPrimitive(WaitableSetNew.new);
            case 'canon.waitable-set.drop':
              primitive = (linker) =>
                  linker.component.addCanonPrimitive(WaitableSetDrop.new);
            case 'canon.waitable.join':
              primitive = (linker) =>
                  linker.component.addCanonPrimitive(WaitableJoin.new);
            case 'canon.future<void>.new':
              primitive = (linker) => linker.component.addCanonPrimitive(
                (f) => FutureNew(f, linker.mapType(FutureAbiType(null))),
              );
            case 'canon.future<void>.read':
              primitive = (linker) => linker.component.addCanonPrimitive((f) {
                final read = FutureRead(f, linker.mapType(FutureAbiType(null)));
                read.async = true;
                return read;
              });
            case 'canon.future<void>.write':
              primitive = (linker) => linker.component.addCanonPrimitive((f) {
                final read = FutureWrite(
                  f,
                  linker.mapType(FutureAbiType(null)),
                );
                read.async = true;
                return read;
              });
            case 'canon.future<void>.drop-read':
              primitive = (linker) => linker.component.addCanonPrimitive(
                (f) =>
                    FutureDropReadable(f, linker.mapType(FutureAbiType(null))),
              );
            case 'canon.future<void>.drop-write':
              primitive = (linker) => linker.component.addCanonPrimitive(
                (f) =>
                    FutureDropWritable(f, linker.mapType(FutureAbiType(null))),
              );
            case 'canon.subtask.drop':
              primitive = (linker) =>
                  linker.component.addCanonPrimitive(CanonSubtaskDrop.new);
            case 'canon.subtask.cancel':
              primitive = (linker) => linker.component.addCanonPrimitive(
                (f) => CanonSubtaskCancel(
                  f,
                  // TODO: Change this to be async once it doesn't require an
                  // experimental option anymore.
                  async: false,
                ),
              );
            default:
              throw UnsupportedError('Unsupported canon ${import.name}');
          }

          abi.imports.add(
            ImportedFunction.exists(
              importName: import.name,
              lowerOptions: const CanonicalOptions(),
              resolve: (linker, options) =>
                  primitive(linker).createdCoreFunction,
            ),
          );

          continue;
        }

        throw CompilerFailure(
          'Import component.${import.name} is not registered in ABI.',
        );
      }

      throw 'TODO: Unknown import ${import.module}:${import.name}';
    }

    for (final removedImport in _patchFunctions.keys) {
      module.imports.functions.remove(removedImport);
      module.imports.all.remove(removedImport);
    }

    logger.fine('Patching ${_patchFunctions.length} functions');
    var patchedReferences = 0;
    for (final function in module.functions.defined) {
      for (final instr in function.body.instructions) {
        if (instr is w.Call) {
          final replacement = _patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
        if (instr is w.RefFunc) {
          final replacement = _patchFunctions[instr.function];
          if (replacement != null) {
            instr.function = replacement;
            patchedReferences++;
          }
        }
      }
    }

    logger.fine('Patched $patchedReferences references');
    finalizeImportsAndDefinitions(
      module.functions.imported,
      module.functions.defined,
    );
  }

  void _removeExports(Set<String> expectedExports) {
    for (final export in _exports.values) {
      if (!expectedExports.remove(export.name)) {
        module.exports.exported.remove(export);
      }
    }

    if (expectedExports.isNotEmpty) {
      throw ArgumentError('Expected compiled app to export $expectedExports');
    }
  }

  void _runMainOnInstantiation() {
    final mainFunction =
        (_exports[r'$invokeMain'] as w.FunctionExport).function;
    final argsArrayType =
        (mainFunction.type.inputs[0] as w.RefType).containedDefType
            as w.ArrayType;

    final instructionsToInvokeMain = [
      if (module.start case final oldStart?) w.Call(oldStart),

      w.I32Const(0),
      w.ArrayNewDefault(argsArrayType),
      w.Call(mainFunction),
    ];
    final emptyFunctionType = module.types.defined
        .whereType<w.FunctionType>()
        .firstWhere((e) => e.inputs.isEmpty && e.outputs.isEmpty);

    final startFunction = w.DefinedFunction(
      module,
      w.Instructions(
        [],
        {},
        [...instructionsToInvokeMain, w.End()],
        null,
        [],
        null,
      ),
      w.FinalizableIndex(),
      emptyFunctionType,
      '_componentStart',
    );
    startFunction.finalizableIndex.value =
        module.functions.defined.last.index + 1;
    module.functions.defined.add(startFunction);
    module.start = startFunction;
  }
}

const _runtimeImportName = 'libc';

const _rewriteToRuntimeImports = {
  'mathPow',
  'mathAtan2',
  'mathSin',
  'mathCos',
  'mathTan',
  'mathAcos',
  'mathAsin',
  'mathAtan',
  'mathExp',
  'mathLog',
};

abstract base class _ComponentImport {
  const _ComponentImport();

  bool addTo(
    ProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  );

  /// Whether the module still imports `dart.<name>`: dart2wasm only drops
  /// those imports under DCE when the corresponding SDK entry point is
  /// unused, so their presence is the "is this feature used" signal.
  static bool functionUsed(ModuleTransformer transformer, String name) {
    return transformer.module.imports.functions.any(
      (e) => e.module == 'dart' && e.name == name,
    );
  }
}

/// Rewrites the `dart.print` import into a `wasi:cli/stdout` dependency.
///
/// The embedder export in pkg:wasm_components consumes the rewritten import by
/// creating a `stream<u8>` with the canon primitives named
/// `implicitImport_stdoutStream*` and handing it to `write-via-stream`.
final class _PrintImports extends _ComponentImport {
  const _PrintImports();

  @override
  bool addTo(
    ProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    // Unlike the randomness rewrite below, this deliberately ignores
    // `implicitWasiDependencies`: the `component.implicitImport_stdout*`
    // imports are declared by the embedder in pkg:wasm_components itself, so
    // they are present in every module linking that embedder (dart2wasm emits
    // the `dart.print` import unconditionally, even for programs that never
    // print). Not registering them would make the component-import check
    // below reject the module. The flag keeps gating imports the compiler
    // adds on Dart's behalf, where a same-name export fallback exists.
    const typesName = 'wasi:cli/types@0.3.0';
    const stdoutName = 'wasi:cli/stdout@0.3.0';

    final typesInterface = abi.interfaces.putIfAbsent(typesName, () {
      return AbiInterface(typesName)
        ..exportedTypes['error-code'] = EnumAbiType(const [
          'io',
          'illegal-byte-sequence',
          'pipe',
        ]);
    });

    // The `error-code` type as seen from `wasi:cli/stdout`, which imports it
    // from `wasi:cli/types`. Both live in the same package, and the stdout
    // interface re-exports it under the same name.
    final errorCodeInStdout = ImportedAbiType(
      typesInterface,
      'error-code',
      inSameInterface: typesInterface.exportedTypes['error-code'],
    );

    final stdoutInterface = abi.interfaces.putIfAbsent(stdoutName, () {
      return AbiInterface(stdoutName)
        ..exportedFunctions['write-via-stream'] = AbiFunction(
          parameters: [('data', StreamAbiType(SimpleAbiType.primitive(.u8)))],
          result: FutureAbiType(ResultAbiType(error: errorCodeInStdout)),
        );
    });

    final coreImportName = 'implicitImport_stdoutWriteViaStream';
    abi.imports.add(
      ImportedFunction.exists(
        importName: coreImportName,
        lowerOptions: const CanonicalOptions(),
        resolve: ImportedFunction.importedFromInstance(
          stdoutInterface,
          'write-via-stream',
        ),
      ),
    );

    // The canon primitives operating on `stream<u8>` which the embedder uses
    // to create the stream handed to `write-via-stream`.
    void addStreamPrimitive(
      String suffix,
      CanonPrimitive Function(
        CoreFunctionIndex,
        component_types.ModelTypeReference,
      )
      create, {
      bool isAsync = false,
      bool usesMemory = false,
    }) {
      abi.imports.add(
        ImportedFunction.exists(
          importName: 'implicitImport_stdoutStream$suffix',
          lowerOptions: CanonicalOptions(
            isAsync: isAsync,
            usesMemory: usesMemory,
          ),
          resolve: (linker, options) {
            final streamType = linker.mapType(
              StreamAbiType(SimpleAbiType.primitive(.u8)),
            );

            final primitive = linker.component.addCanonPrimitive(
              (index) => create(index, streamType),
            );
            if (primitive case final CanonicalHasOptions hasOptions) {
              options.applyTo(linker, hasOptions);
            }
            return primitive.createdCoreFunction;
          },
        ),
      );
    }

    addStreamPrimitive('New', (index, type) => StreamNew(index, type));
    addStreamPrimitive(
      'Write',
      (index, type) => StreamWrite(index, type),
      isAsync: true,
      usesMemory: true,
    );
    addStreamPrimitive(
      'Read',
      (index, type) => StreamRead(index, type),
      isAsync: true,
      usesMemory: true,
    );
    addStreamPrimitive(
      'DropReadable',
      (index, type) => StreamDropReadable(index, type),
    );
    addStreamPrimitive(
      'DropWritable',
      (index, type) => StreamDropWritable(index, type),
    );

    // The canon primitives operating on the `future<result<_, error-code>>`
    // returned by `write-via-stream`.
    void addFuturePrimitive(
      String suffix,
      CanonPrimitive Function(
        CoreFunctionIndex,
        component_types.ModelTypeReference,
      )
      create, {
      bool isAsync = false,
      bool usesMemory = false,
    }) {
      abi.imports.add(
        ImportedFunction.exists(
          importName: 'implicitImport_stdoutFuture$suffix',
          lowerOptions: CanonicalOptions(
            isAsync: isAsync,
            usesMemory: usesMemory,
          ),
          resolve: (linker, options) {
            final futureType = linker.mapType(
              FutureAbiType(ResultAbiType(error: errorCodeInStdout)),
            );

            final primitive = linker.component.addCanonPrimitive(
              (index) => create(index, futureType),
            );
            if (primitive case final CanonicalHasOptions hasOptions) {
              options.applyTo(linker, hasOptions);
            }
            return primitive.createdCoreFunction;
          },
        ),
      );
    }

    addFuturePrimitive('New', (index, type) => FutureNew(index, type));
    addFuturePrimitive(
      'Write',
      (index, type) => FutureWrite(index, type),
      isAsync: true,
      usesMemory: true,
    );
    addFuturePrimitive(
      'Read',
      (index, type) => FutureRead(index, type),
      isAsync: true,
      usesMemory: true,
    );
    addFuturePrimitive(
      'DropReadable',
      (index, type) => FutureDropReadable(index, type),
    );
    addFuturePrimitive(
      'DropWritable',
      (index, type) => FutureDropWritable(index, type),
    );

    return true;
  }
}

final class _RandomImports extends _ComponentImport {
  const _RandomImports();

  @override
  bool addTo(
    ProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    if (!transformer.implicitWasiDependencies) return false;

    final isSecure = function.name == 'randomIntSecure';
    final interface = isSecure
        ? _lookupSecureRandom(abi)
        : _lookupInsecureRandom(abi);
    final methodName = isSecure ? 'get-random-u64' : 'get-insecure-random-u64';

    final coreImportName = 'implicitImport_${function.name}';
    final import = w.ImportedFunction(
      transformer.module,
      'component',
      coreImportName,
      w.FinalizableIndex(),
      function.type,
    );
    transformer.module.imports
      ..all.add(import)
      ..functions.add(import);

    abi.imports.add(
      ImportedFunction.exists(
        importName: coreImportName,
        lowerOptions: const CanonicalOptions(),
        resolve: ImportedFunction.importedFromInstance(interface, methodName),
      ),
    );
    transformer._patchFunctions[function] = import;
    return true;
  }

  AbiInterface _lookupInsecureRandom(ProgramAbi abi) {
    const fullName = 'wasi:random/insecure@0.3.0';

    return abi.interfaces.putIfAbsent(fullName, () {
      return AbiInterface(fullName)
        ..exportedFunctions['get-insecure-random-bytes'] = _generateBytes()
        ..exportedFunctions['get-insecure-random-u64'] = _generateU64();
    });
  }

  AbiInterface _lookupSecureRandom(ProgramAbi abi) {
    const fullName = 'wasi:random/random@0.3.0';

    return abi.interfaces.putIfAbsent(fullName, () {
      return AbiInterface(fullName)
        ..exportedFunctions['get-random-bytes'] = _generateBytes()
        ..exportedFunctions['get-random-u64'] = _generateU64();
    });
  }

  AbiFunction _generateBytes() {
    return AbiFunction(
      async: false,
      parameters: const [('max-len', SimpleAbiType.primitive(.u64))],
      result: const VariableLengthListAbiType(SimpleAbiType.primitive(.u8)),
    );
  }

  AbiFunction _generateU64() {
    return AbiFunction(
      async: false,
      parameters: [],
      result: SimpleAbiType.primitive(.u64),
    );
  }
}

final class _ClockImports extends _ComponentImport {
  const _ClockImports();

  @override
  bool addTo(
    ProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    // TODO: Respect transformer.implicitWasiDependencies

    switch (function.name) {
      case 'wasi_now':
        if (!_ComponentImport.functionUsed(transformer, 'currentTime')) {
          _stubPtr(transformer, function);
          break;
        }

        final systemClock = _lookupSystemClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_systemClockNow';
        abi.imports.add(
          ImportedFunction.exists(
            importName: function.name,
            lowerOptions: CanonicalOptions(usesMemory: true),
            resolve: ImportedFunction.importedFromInstance(systemClock, 'now'),
          ),
        );
      case 'wasi_iana_id':
        if (!_ComponentImport.functionUsed(transformer, 'timeZoneNameForClampedSeconds')) {
          _stubPtr(transformer, function);
          break;
        }

        final timezone = _lookupTimezone(abi);
        function.module = 'component';
        function.name = 'implicitImport_timezoneIanaId';
        abi.imports.add(
          ImportedFunction.exists(
            importName: function.name,
            lowerOptions: CanonicalOptions(
              usesMemory: true,
              usesString: true,
              usesRealloc: true,
            ),
            resolve: ImportedFunction.importedFromInstance(timezone, 'iana-id'),
          ),
        );
      case 'wasi_monotonic_now':
        if (!_ComponentImport.functionUsed(transformer, 'monotonicClockTicks')) {
          _stubReturningI64(transformer, function);
          break;
        }
        final clock = _lookupMonotonicClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_monotonicTicks';
        abi.imports.add(
          ImportedFunction.exists(
            importName: function.name,
            lowerOptions: const CanonicalOptions(),
            resolve: ImportedFunction.importedFromInstance(clock, 'now'),
          ),
        );
      case 'wasi_monotonic_getResolution':
        if (!_ComponentImport.functionUsed(transformer, 'monotonicClockFrequency') &&
            !_ComponentImport.functionUsed(transformer, 'monotonicClockTicks')) {
          _stubReturningI64(transformer, function);
          break;
        }
        final clock = _lookupMonotonicClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_monotonicDuration';
        abi.imports.add(
          ImportedFunction.exists(
            importName: function.name,
            lowerOptions: const CanonicalOptions(),
            resolve: ImportedFunction.importedFromInstance(
              clock,
              'get-resolution',
            ),
          ),
        );
      case 'wasi_monotonic_waitFor':
        final clock = _lookupMonotonicClock(abi);
        function.module = 'component';
        function.name = 'implicitImport_monotonicWaitFor';
        abi.imports.add(
          ImportedFunction.exists(
            importName: function.name,
            lowerOptions: const CanonicalOptions(isAsync: true),
            resolve: ImportedFunction.importedFromInstance(clock, 'wait-for'),
          ),
        );
    }

    return true;
  }

  /// Replaces the `wasiNowPtr()` import with a stub to avoid dependencies.
  void _stubPtr(
    ModuleTransformer transformer,
    w.ImportedFunction importedFunction,
  ) {
    final stubFunction = w.DefinedFunction(
      transformer.module,
      w.Instructions([], {}, [w.End()], null, [], null),
      w.FinalizableIndex(),
      importedFunction.type,
    );
    transformer.module.functions.defined.add(stubFunction);
    transformer._patchFunctions[importedFunction] = stubFunction;
  }

  // Replaces `wasiMonotonicNow()` and `wasiMonotonicGetResolution` with a stub.
  void _stubReturningI64(
    ModuleTransformer transformer,
    w.ImportedFunction importedFunction,
  ) {
    final stubFunction = w.DefinedFunction(
      transformer.module,
      w.Instructions([], {}, [w.I64Const(0), w.End()], null, [], null),
      w.FinalizableIndex(),
      importedFunction.type,
    );
    transformer.module.functions.defined.add(stubFunction);
    transformer._patchFunctions[importedFunction] = stubFunction;
  }

  AbiInterface _lookupSystemClock(ProgramAbi abi) {
    const fullName = 'wasi:clocks/system-clock@0.3.0';

    return abi.interfaces.putIfAbsent(fullName, () {
      final instantType = RecordAbiType(
        fields: const [
          ('seconds', SimpleAbiType.primitive(.s64)),
          ('nanoseconds', SimpleAbiType.primitive(.u32)),
        ],
      );

      return AbiInterface(fullName)
        ..exportedTypes['instant'] = instantType
        ..exportedFunctions['now'] = AbiFunction(result: instantType)
        ..exportedFunctions['get-resolution'] = AbiFunction(
          result: SimpleAbiType.primitive(.u64),
        );
    });
  }

  AbiInterface _lookupTimezone(ProgramAbi abi) {
    const fullName = 'wasi:clocks/timezone@0.3.0';

    return abi.interfaces.putIfAbsent(fullName, () {
      return AbiInterface(fullName)
        ..exportedFunctions['iana-id'] = AbiFunction(
          result: const OptionAbiType(SimpleAbiType.string()),
        );
    });
  }

  AbiInterface _lookupMonotonicClock(ProgramAbi abi) {
    const fullName = 'wasi:clocks/monotonic-clock@0.3.0';

    return abi.interfaces.putIfAbsent(fullName, () {
      return AbiInterface(fullName)
        ..exportedFunctions['now'] = const AbiFunction(
          result: SimpleAbiType.primitive(.u64),
        )
        ..exportedFunctions['get-resolution'] = const AbiFunction(
          result: SimpleAbiType.primitive(.u64),
        )
        ..exportedFunctions['wait-for'] = const AbiFunction(
          async: true,
          parameters: [('how-long', SimpleAbiType.primitive(.u64))],
        );
    });
  }
}

/// Rewrites the SDK's `dart.stackTrace*` imports into a capture dependency.
///
/// A stack trace of the running wasm exists only in the host - wasmtime walks
/// its frame table, Node formats `Error().stack` - so the embedder's
/// `stackTraceGetCurrent` asks the host to render the trace into linear
/// memory and reads it back as a guest string. The `stackTraceToString` half
/// of the SDK contract renders a captured trace; this embedder captures at
/// `getCurrent` time and re-captures on `toString`, so both imports resolve
/// to the same host capture function.
///
/// The guest side lives in `stack_trace_capture.dart` in pkg:wasm_components;
/// its `component.implicitImport_stackTraceCaptureUtf16` import is declared
/// there, like the stdout machinery this pattern follows.
final class _StackTraceImports extends _ComponentImport {
  const _StackTraceImports();

  @override
  bool addTo(
    ProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    const captureImportName = 'implicitImport_stackTraceCaptureUtf16';

    if (!_ComponentImport.functionUsed(transformer, 'stackTraceGetCurrent') &&
        !_ComponentImport.functionUsed(transformer, 'stackTraceToString')) {
      // The SDK patch hides its own frames, but dart2wasm only drops the
      // `dart.stackTrace*` imports under DCE when no StackTrace is ever
      // read, so both absent together means neither is used: stub the
      // capture and keep no host dependency.
      _stubStackTraceCapture(transformer, function);
      return true;
    }

    final alreadyRegistered = abi.imports.any(
      (import) => import.importName == captureImportName,
    );
    if (!alreadyRegistered) {
      abi.imports.add(
        ImportedFunction.exists(
          importName: captureImportName,
          // Memory + realloc are what let a host render the trace into guest
          // linear memory through the component ABI: the canonical `string`
          // return is written with the module's own allocator, so the host
          // never needs a raw `(i32) -> i32` backdoor into the guest heap.
          lowerOptions: const CanonicalOptions(
            usesMemory: true,
            usesString: true,
            usesRealloc: true,
          ),
          // Resolved at link time: the module declares the import (the
          // embedder's stack_trace_capture.dart), this entry only tells the
          // ABI that the name is expected to be there.
          resolve: ImportedFunction.importedFromInstance(
            _stackTraceInterface(abi),
            'capture-utf16',
          ),
        ),
      );
    }
    return true;
  }

  /// The host interface carrying the capture function. Named like a WIT
  /// package interface (`ns:package/interface@version`) so the component's
  /// import is a valid extern name, versioned like the wasi interfaces the
  /// other implicit dependencies use.
  AbiInterface _stackTraceInterface(ProgramAbi abi) {
    const fullName = 'wasm:dart/trace@1.0.0';
    return abi.interfaces.putIfAbsent(fullName, () {
      return AbiInterface(fullName)
        ..exportedFunctions['capture-utf16'] = const AbiFunction(
          parameters: [('capacity', SimpleAbiType.primitive(.u32))],
          result: SimpleAbiType.string(),
        );
    });
  }

  /// A capture stub: writes a null pointer and zero length into the return
  /// area the retptr call passed, i.e. "nothing captured" without touching
  /// the allocator. Reading a null pointer back yields no string, so
  /// `stackTraceGetCurrent` falls back to its constant.
  void _stubStackTraceCapture(
    ModuleTransformer transformer,
    w.ImportedFunction importedFunction,
  ) {
    final type = importedFunction.type;
    final memory = transformer.module.memories.imported.firstWhere(
      (memory) => memory.module == 'libc' && memory.name == 'memory',
    );
    // The parameters, in order: the capture capacity (unused) and the
    // address of the two-word return area.
    final capacityLocal = w.Local(0, w.NumType.i32);
    final returnAreaLocal = w.Local(1, w.NumType.i32);
    final body = w.Instructions(
      [capacityLocal, returnAreaLocal],
      {},
      [
        // A null pointer and a zero length: nothing captured.
        w.LocalGet(returnAreaLocal),
        w.I32Const(0),
        w.I32Store(w.MemoryOffsetAlign(memory, offset: 0, align: 2)),
        w.LocalGet(returnAreaLocal),
        w.I32Const(0),
        w.I32Store(w.MemoryOffsetAlign(memory, offset: 4, align: 2)),
        w.End(),
      ],
      null,
      [],
      null,
    );
    final stubFunction = w.DefinedFunction(
      transformer.module,
      body,
      w.FinalizableIndex(),
      type,
      'stackTraceCaptureStub',
    );
    transformer.module.functions.defined.add(stubFunction);
    transformer._patchFunctions[importedFunction] = stubFunction;
  }
}

/// Rewrites the `dart.timelineStreamEnabled`/`dart.reportTaskEvent` imports
/// into a `wasm:dart/timeline` host dependency.
///
/// The stream-enabled answer lives in the embedder export (always `true`,
/// see `weak.dart`); `reportTaskEvent` stays a same-name embedder export
/// that adapts the SDK's externref strings into the canonical
/// `(pointer, length)` pairs the host interface carries. This replacer
/// registers that host dependency. The embedder source is always compiled
/// in (it is exported), so its
/// `component.implicitImport_timelineReportTaskEvent` import is declared
/// whether or not dart2wasm's DCE kept the SDK's `dart.*` timeline imports
/// - when both are gone nothing can produce an event, and the declared
/// import is rewired to a stub answering "not recorded" so the component
/// keeps no host dependency it cannot use.
final class _TimelineImports extends _ComponentImport {
  const _TimelineImports();

  @override
  bool addTo(
    ProgramAbi abi,
    ModuleTransformer transformer,
    w.ImportedFunction function,
  ) {
    const reportImportName = 'implicitImport_timelineReportTaskEvent';

    if (!_ComponentImport.functionUsed(transformer, 'timelineStreamEnabled') &&
        !_ComponentImport.functionUsed(transformer, 'reportTaskEvent')) {
      _stubTimelineReport(transformer, function);
      return true;
    }

    final alreadyRegistered = abi.imports.any(
      (import) => import.importName == reportImportName,
    );
    if (!alreadyRegistered) {
      abi.imports.add(
        ImportedFunction.exists(
          importName: reportImportName,
          // The two strings arrive as `(pointer, length)` UTF-16 pairs in
          // the module's linear memory, so the canonical lowering needs the
          // memory (and string-encoding) options - no realloc: the guest
          // allocated the units itself and frees them after the call.
          lowerOptions: const CanonicalOptions(
            usesMemory: true,
            usesString: true,
          ),
          // Resolved at link time: the module declares the import (the
          // embedder's weak.dart), this entry only tells the ABI that the
          // name is expected to be there.
          resolve: ImportedFunction.importedFromInstance(
            _timelineInterface(abi),
            'record-task-event',
          ),
        ),
      );
    }
    return true;
  }

  /// The host interface carrying the event sink. Named like a WIT package
  /// interface (`ns:package/interface@version`) so the component's import
  /// is a valid extern name, versioned like the wasi interfaces the other
  /// implicit dependencies use.
  AbiInterface _timelineInterface(ProgramAbi abi) {
    const fullName = 'wasm:dart/timeline@1.0.0';
    return abi.interfaces.putIfAbsent(fullName, () {
      return AbiInterface(fullName)
        ..exportedFunctions['record-task-event'] = const AbiFunction(
          parameters: [
            ('event-type', SimpleAbiType.primitive(.u8)),
            ('task-id', SimpleAbiType.primitive(.s32)),
            ('flow-id', SimpleAbiType.primitive(.s32)),
            ('name', SimpleAbiType.string()),
            ('arguments-as-json', SimpleAbiType.string()),
          ],
          result: SimpleAbiType.primitive(.bool),
        );
    });
  }

  /// A stub answering `false` ("not recorded") with the shape the embedder
  /// expects: the event type, ids and the two `(pointer, length)` string
  /// pairs are all ignored, so no memory is touched and nothing is freed.
  void _stubTimelineReport(
    ModuleTransformer transformer,
    w.ImportedFunction importedFunction,
  ) {
    final type = importedFunction.type;
    final params = [
      for (var i = 0; i < type.inputs.length; i++) w.Local(i, w.NumType.i32),
    ];
    final body = w.Instructions(
      params,
      {},
      [w.I32Const(0), w.End()],
      null,
      [],
      null,
    );
    final stubFunction = w.DefinedFunction(
      transformer.module,
      body,
      w.FinalizableIndex(),
      type,
      'timelineReportStub',
    );
    transformer.module.functions.defined.add(stubFunction);
    transformer._patchFunctions[importedFunction] = stubFunction;
  }
}
