import 'dart:convert';
import 'dart:io';

// Regenerates lib/src/embedder/unicode_tables.dart, the case-conversion
// tables the regexp engine canonicalizes with:
//
//  - `caseFoldPairs`: the simple (status `S`) and common (status `C`) case
//    folding mappings of CaseFolding.txt. ECMAScript's `Canonicalize` uses
//    these when the `u` flag is set and matching is case-insensitive.
//  - `simpleUppercasePairs`: the simple uppercase mappings (field 12 of
//    UnicodeData.txt) restricted to code points of the basic multilingual
//    plane. `Canonicalize` without the `u` flag applies them to single UTF-16
//    code units and rejects mappings that would leave the plane.
//
// Usage:
//
//   dart run tool/generate_unicode_tables.dart [CaseFolding.txt [UnicodeData.txt]]
//
// Without arguments the files are downloaded from the Unicode 16.0.0 UCD.
const _caseFoldingUrl =
    'https://www.unicode.org/Public/16.0.0/ucd/CaseFolding.txt';
const _unicodeDataUrl =
    'https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt';

Future<void> main(List<String> args) async {
  final folding = await _readInput(
    args.isNotEmpty ? args[0] : null,
    _caseFoldingUrl,
    'CaseFolding.txt',
  );
  final unicodeData = await _readInput(
    args.length > 1 ? args[1] : null,
    _unicodeDataUrl,
    'UnicodeData.txt',
  );

  final folds = <List<int>>[];
  for (final line in folding.split('\n')) {
    final entry = line.split('#')[0].split(';');
    if (entry.length < 3) continue;
    final status = entry[1].trim();
    if (status != 'C' && status != 'S') continue;
    folds.add([
      int.parse(entry[0].trim(), radix: 16),
      entry[2].trim().split(' ').map((h) => int.parse(h, radix: 16)).single,
    ]);
  }
  folds.sort((a, b) => a[0].compareTo(b[0]));

  final uppers = <List<int>>[];
  for (final line in unicodeData.split('\n')) {
    final fields = line.split(';');
    if (fields.length < 13) continue;
    final code = int.parse(fields[0], radix: 16);
    final mapping = fields[12];
    if (mapping.isEmpty) continue;
    final upper = int.parse(mapping, radix: 16);
    // Without the `u` flag, `Canonicalize` maps single UTF-16 code units and
    // keeps a code point whose uppercase image is not one code unit.
    if (upper > 0xFFFF) continue;
    if (upper == code) continue;
    uppers.add([code, upper]);
  }
  uppers.sort((a, b) => a[0].compareTo(b[0]));

  // Folding images must be fixed points, or folding a member and folding the
  // input would not define an equivalence relation.
  final foldOf = <int, int>{for (final pair in folds) pair[0]: pair[1]};
  for (final pair in folds) {
    final image = pair[1];
    if (foldOf[image] != null && foldOf[image] != image) {
      throw 'fold(${image.toRadixString(16)}) = ${foldOf[image]!.toRadixString(16)}';
    }
  }

  final buffer = StringBuffer('''
// dart format off
// Generated by tool/generate_unicode_tables.dart

// ignore: import_internal_library
import 'dart:_wasm';

''');
  buffer.writeln(
    _arrayDoc(
      'caseFoldPairs',
      folds,
      'Simple (`S`) and common (`C`) case folding mappings, sorted by source',
      'code point. Slot `2 * i` holds a source, slot `2 * i + 1` its image.',
      'Images are fixed points of the fold. Used to canonicalize when the',
      '`u` flag is set and matching is case-insensitive.',
    ),
  );
  buffer.writeln();
  buffer.writeln(
    _arrayDoc(
      'simpleUppercasePairs',
      uppers,
      'Simple uppercase mappings of the basic multilingual plane, sorted by',
      'source code point. Used to canonicalize case-insensitive matches',
      'without the `u` flag, where characters whose image would cross from',
      'outside ASCII into it stay unchanged (checked at run time).',
    ),
  );
  File('lib/src/embedder/unicode_tables.dart')
      .writeAsStringSync(buffer.toString());
}

String _arrayDoc(
  String name,
  List<List<int>> pairs,
  String description,
  String more,
  String more2,
  String more3,
) {
  final values = [for (final pair in pairs) ...pair];
  return '''
/// $description
/// $more
/// $more2
/// $more3
const WasmArray<WasmI32> $name = WasmArray.literal([${values.join(', ')}]);''';
}

Future<String> _readInput(String? path, String url, String name) async {
  if (path != null) return File(path).readAsString();
  final client = HttpClient();
  try {
    final request = await client.getUrl(Uri.parse(url));
    final response = await request.close();
    return await response.transform(utf8.decoder).join();
  } finally {
    client.close();
  }
}
